#ifndef _KERNEL_ARCH_I386_SERIAL_H
#define _KERNEL_ARCH_I386_SERIAL_H

#define SERIAL_RX_BUFFER 0
#define SERIAL_TX_BUFFER 0
#define SERIAL_INT_ENABLE_REGISTER 1
#define SERIAL_BAUD_RATE_LSB 0
#define SERIAL_BAUD_RATE_MSB 1
#define SERIAL_INTERRUPT_ID 2
#define SERIAL_FIFO_CONTROL_REGISTER 2
#define SERIAL_LINE_CONTROL_REGISTER 3
#define SERIAL_MODEM_CONTROL_REGISTER 4
#define SERIAL_LINE_STATUS_REGISTER 5
#define SERIAL_MODEM_STATUS_REGISTER 6
#define SERIAL_SCRATCH_REGISTER 7

#define SERIAL_DLAB 0xF0
#define SERIAL_BREAK_ENABLE 0x80
#define SERIAL_DATA(X) (X)
#define SERIAL_STOP(X) (X << 2)
#define SERIAL_PARITY_NONE 0
#define SERIAL_PARITY_ODD 0x4
#define SERIAL_PARITY_EVEN 0xC
#define SERIAL_PARITY_MARK 0x14
#define SERIAL_PARITY_SPACE 0x1C

#define SERIAL_MODEM_LOOPBACK 0x10

#define SERIAL_THRE 0x20

int serial_init();
void serial_write(char c);

#endif